### ISSUE TITLE
Feature request: way to get output as array instead of object

### ISSUE THREAD

**Issue by jedwards1211** [shannonmoeller/require-glob#19]
In most cases where I use this to glob `someDir/**/*.js` having a flat array of results would actually be more convenient for what I'm doing than a nested object.  But the way `require-glob` is designed, the `reduce` step necessarily takes and returns an object, so there's not really a handy way to get an array out of it.

Would you be open to a PR to extract and export a function that does the glob and returns the results of the mapper, and then make the main function call that and then run the reducer on it?

**Comment by jedwards1211** [comment]
I guess I could just use `glob` and `require` by themselves.  I dunno.  Slightly awkward balance of convenience concerns here

**Comment by shannonmoeller** [comment]
I think we can solve for what you need without a PR. The initial value I pass into the reducer is an object, but it doesn't have to stay an object. It's a little ugly, but would something like this work? Essentially a no-op reducer.

```js
const modules = await requireGlob(['**/*.js', '!cake.js'], {
  reducer(options, list, file) {
    if (!Array.isArray(list)) {
      list = [];
    }

    list.push(file);

    return list;
  }
});
```

**Comment by jedwards1211** [comment]
Yeah that could work, in any case I realized that `require('glob').sync('./test/**/*.js').map(f => require(f))` will work for cases where I need an array.

**Comment by shannonmoeller** [comment]
Yay for simplicity and dropping abstractions when they're no longer helpful!

**Comment by jedwards1211** [comment]
Yup.  I still use this for loading directories of test fixtures though.  Thanks!

**Comment by jedwards1211** [comment]
Fun fact: I added support for `require-glob` in this tool I made: [jscodeshift-build-import-list](https://github.com/codemodsquad/jscodeshift-build-import-list#readme)
