### ISSUE TITLE
file.shortPath is broken for a single, nested file

### ISSUE THREAD

**Issue by kflorence** [shannonmoeller/require-glob#2]
It seems like the logic inside the `trimPaths` method will slice off all common roots, but in the case of only one nested file it strips off too much.

For example, given the glob `source/partials/**/*.hbs` and a single file at `source/partials/layouts/default.hbs` I would expect a `file.shortPath` of `layouts/default.hbs` but instead I get `default.hbs`.

If I add another file to the root of the `source/partials` directory, everything works as expected.

**Comment by shannonmoeller** [comment]
This is the intended behavior. The `trimPaths` method will slice off all directories that are common to each item in the list. If there's only one item, this has the effect of slicing off all directories. I felt that anything beyond this was too opinionated or magical.

If this is not ideal for your needs, I recommend specifying your own `keygen` method with your preferred logic:

``` js
requireGlob.sync('source/partials/**/*.hbs', {
    keygen: function (file) {
        // your custom logic
    }
});
```

If you happen to be using this module by way of `handlebars-registrar` or `gulp-hb`, this can be accomplished by providing a custom [`parsePartialName`](https://github.com/shannonmoeller/handlebars-registrar#parsepartialname-functionobjectstring) method.

**Comment by kflorence** [comment]
Perhaps it is opinionated, but defaulting the `shortPath` to the base of the glob pattern is pretty common in node/gulp-land.

**Comment by shannonmoeller** [comment]
The api allows you to define multiple glob patterns via `globby`. I don't see anyway to support what you're requesting without the possibility of introducing key collisions:

```
src/
|- foo/
|  `- meta.js
`- bar/
   `- meta.js
```

``` js
requireGlob(['src/foo/**/*.js', 'src/bar/**/*.js'], function (data) {
    console.log(data.meta); // foo? bar?
});
```

I'm open to suggestions.
